version: '3.9'

services: 
  web:
    image: dany165/django_dev
    container_name: django_dev
    build: .
    volumes:
     - .:/src/django_dev
    ports: 
     - 8080:8080
    command: python3 manage.py runserver 0.0.0.0:8080
    depends_on: 
     - postgres-db
  
  postgres-db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env 
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  postgres_data:



